package types

// special keys like Ctrl
type SpecialKeyboardKey string

// all types (implementation independent)
const (
	BACKSPACE SpecialKeyboardKey = "BACKSPACE"
	DELETE    SpecialKeyboardKey = "DELETE"
	RETURN    SpecialKeyboardKey = "RETURN"
	TAB       SpecialKeyboardKey = "TAB"
	ESCAPE    SpecialKeyboardKey = "ESCAPE"
	UP        SpecialKeyboardKey = "UP"
	DOWN      SpecialKeyboardKey = "DOWN"
	RIGHT     SpecialKeyboardKey = "RIGHT"
	LEFT      SpecialKeyboardKey = "LEFT"
	HOME      SpecialKeyboardKey = "HOME"
	END       SpecialKeyboardKey = "END"
	PAGEUP    SpecialKeyboardKey = "PAGEUP"
	PAGEDOWN  SpecialKeyboardKey = "PAGEDOWN"

	F1  SpecialKeyboardKey = "F1"
	F2  SpecialKeyboardKey = "F2"
	F3  SpecialKeyboardKey = "F3"
	F4  SpecialKeyboardKey = "F4"
	F5  SpecialKeyboardKey = "F5"
	F6  SpecialKeyboardKey = "F6"
	F7  SpecialKeyboardKey = "F7"
	F8  SpecialKeyboardKey = "F8"
	F9  SpecialKeyboardKey = "F9"
	F10 SpecialKeyboardKey = "F10"
	F11 SpecialKeyboardKey = "F11"
	F12 SpecialKeyboardKey = "F12"
	F13 SpecialKeyboardKey = "F13"
	F14 SpecialKeyboardKey = "F14"
	F15 SpecialKeyboardKey = "F15"
	F16 SpecialKeyboardKey = "F16"
	F17 SpecialKeyboardKey = "F17"
	F18 SpecialKeyboardKey = "F18"
	F19 SpecialKeyboardKey = "F19"
	F20 SpecialKeyboardKey = "F20"
	F21 SpecialKeyboardKey = "F21"
	F22 SpecialKeyboardKey = "F22"
	F23 SpecialKeyboardKey = "F23"
	F24 SpecialKeyboardKey = "F24"

	META        SpecialKeyboardKey = "META"
	LMETA       SpecialKeyboardKey = "LMETA"
	RMETA       SpecialKeyboardKey = "RMETA"
	ALT         SpecialKeyboardKey = "ALT"
	LALT        SpecialKeyboardKey = "LALT"
	RALT        SpecialKeyboardKey = "RALT"
	CONTROL     SpecialKeyboardKey = "CONTROL"
	LCONTROL    SpecialKeyboardKey = "LCONTROL"
	RCONTROL    SpecialKeyboardKey = "RCONTROL"
	SHIFT       SpecialKeyboardKey = "SHIFT"
	LSHIFT      SpecialKeyboardKey = "LSHIFT"
	RSHIFT      SpecialKeyboardKey = "RSHIFT"
	CAPSLOCK    SpecialKeyboardKey = "CAPSLOCK"
	SPACE       SpecialKeyboardKey = "SPACE"
	PRINTSCREEN SpecialKeyboardKey = "PRINTSCREEN"
	INSERT      SpecialKeyboardKey = "INSERT"
	MENU        SpecialKeyboardKey = "MENU"

	NUMPAD_0    SpecialKeyboardKey = "NUMPAD_0"
	NUMPAD_1    SpecialKeyboardKey = "NUMPAD_1"
	NUMPAD_2    SpecialKeyboardKey = "NUMPAD_2"
	NUMPAD_3    SpecialKeyboardKey = "NUMPAD_3"
	NUMPAD_4    SpecialKeyboardKey = "NUMPAD_4"
	NUMPAD_5    SpecialKeyboardKey = "NUMPAD_5"
	NUMPAD_6    SpecialKeyboardKey = "NUMPAD_6"
	NUMPAD_7    SpecialKeyboardKey = "NUMPAD_7"
	NUMPAD_8    SpecialKeyboardKey = "NUMPAD_8"
	NUMPAD_9    SpecialKeyboardKey = "NUMPAD_9"
	NUMPAD_LOCK SpecialKeyboardKey = "NUMPAD_LOCK"

	NUMPAD_DECIMAL SpecialKeyboardKey = "NUMPAD_DECIMAL"
	NUMPAD_PLUS    SpecialKeyboardKey = "NUMPAD_PLUS"
	NUMPAD_MINUS   SpecialKeyboardKey = "NUMPAD_MINUS"
	NUMPAD_MUL     SpecialKeyboardKey = "NUMPAD_MUL"
	NUMPAD_DIV     SpecialKeyboardKey = "NUMPAD_DIV"
	NUMPAD_ENTER   SpecialKeyboardKey = "NUMPAD_ENTER"
	NUMPAD_EQUAL   SpecialKeyboardKey = "NUMPAD_EQUAL"

	AUDIO_VOLUME_MUTE SpecialKeyboardKey = "AUDIO_VOLUME_MUTE"
	AUDIO_VOLUME_DOWN SpecialKeyboardKey = "AUDIO_VOLUME_DOWN"
	AUDIO_VOLUME_UP   SpecialKeyboardKey = "AUDIO_VOLUME_UP"
	AUDIO_PLAY        SpecialKeyboardKey = "AUDIO_PLAY"
	AUDIO_STOP        SpecialKeyboardKey = "AUDIO_STOP"
	AUDIO_PAUSE       SpecialKeyboardKey = "AUDIO_PAUSE"
	AUDIO_PREV        SpecialKeyboardKey = "AUDIO_PREV"
	AUDIO_NEXT        SpecialKeyboardKey = "AUDIO_NEXT"
)
