package keyboard

import "github.com/benu-cloud/benu-livestreaming-gst/pkg/controls/types"

const (
	KEYBOARD_BACKSPACE types.SpecialKeyboardKey = "BACKSPACE"
	KEYBOARD_DELETE    types.SpecialKeyboardKey = "DELETE"
	KEYBOARD_RETURN    types.SpecialKeyboardKey = "RETURN"
	KEYBOARD_TAB       types.SpecialKeyboardKey = "TAB"
	KEYBOARD_ESCAPE    types.SpecialKeyboardKey = "ESCAPE"
	KEYBOARD_UP        types.SpecialKeyboardKey = "UP"
	KEYBOARD_DOWN      types.SpecialKeyboardKey = "DOWN"
	KEYBOARD_RIGHT     types.SpecialKeyboardKey = "RIGHT"
	KEYBOARD_LEFT      types.SpecialKeyboardKey = "LEFT"
	KEYBOARD_HOME      types.SpecialKeyboardKey = "HOME"
	KEYBOARD_END       types.SpecialKeyboardKey = "END"
	KEYBOARD_PAGEUP    types.SpecialKeyboardKey = "PAGEUP"
	KEYBOARD_PAGEDOWN  types.SpecialKeyboardKey = "PAGEDOWN"

	KEYBOARD_F1  types.SpecialKeyboardKey = "F1"
	KEYBOARD_F2  types.SpecialKeyboardKey = "F2"
	KEYBOARD_F3  types.SpecialKeyboardKey = "F3"
	KEYBOARD_F4  types.SpecialKeyboardKey = "F4"
	KEYBOARD_F5  types.SpecialKeyboardKey = "F5"
	KEYBOARD_F6  types.SpecialKeyboardKey = "F6"
	KEYBOARD_F7  types.SpecialKeyboardKey = "F7"
	KEYBOARD_F8  types.SpecialKeyboardKey = "F8"
	KEYBOARD_F9  types.SpecialKeyboardKey = "F9"
	KEYBOARD_F10 types.SpecialKeyboardKey = "F10"
	KEYBOARD_F11 types.SpecialKeyboardKey = "F11"
	KEYBOARD_F12 types.SpecialKeyboardKey = "F12"
	KEYBOARD_F13 types.SpecialKeyboardKey = "F13"
	KEYBOARD_F14 types.SpecialKeyboardKey = "F14"
	KEYBOARD_F15 types.SpecialKeyboardKey = "F15"
	KEYBOARD_F16 types.SpecialKeyboardKey = "F16"
	KEYBOARD_F17 types.SpecialKeyboardKey = "F17"
	KEYBOARD_F18 types.SpecialKeyboardKey = "F18"
	KEYBOARD_F19 types.SpecialKeyboardKey = "F19"
	KEYBOARD_F20 types.SpecialKeyboardKey = "F20"
	KEYBOARD_F21 types.SpecialKeyboardKey = "F21"
	KEYBOARD_F22 types.SpecialKeyboardKey = "F22"
	KEYBOARD_F23 types.SpecialKeyboardKey = "F23"
	KEYBOARD_F24 types.SpecialKeyboardKey = "F24"

	KEYBOARD_META        types.SpecialKeyboardKey = "META"
	KEYBOARD_LMETA       types.SpecialKeyboardKey = "LMETA"
	KEYBOARD_RMETA       types.SpecialKeyboardKey = "RMETA"
	KEYBOARD_ALT         types.SpecialKeyboardKey = "ALT"
	KEYBOARD_LALT        types.SpecialKeyboardKey = "LALT"
	KEYBOARD_RALT        types.SpecialKeyboardKey = "RALT"
	KEYBOARD_CONTROL     types.SpecialKeyboardKey = "CONTROL"
	KEYBOARD_LCONTROL    types.SpecialKeyboardKey = "LCONTROL"
	KEYBOARD_RCONTROL    types.SpecialKeyboardKey = "RCONTROL"
	KEYBOARD_SHIFT       types.SpecialKeyboardKey = "SHIFT"
	KEYBOARD_LSHIFT      types.SpecialKeyboardKey = "LSHIFT"
	KEYBOARD_RSHIFT      types.SpecialKeyboardKey = "RSHIFT"
	KEYBOARD_CAPSLOCK    types.SpecialKeyboardKey = "CAPSLOCK"
	KEYBOARD_SPACE       types.SpecialKeyboardKey = "SPACE"
	KEYBOARD_PRINTSCREEN types.SpecialKeyboardKey = "PRINTSCREEN"
	KEYBOARD_INSERT      types.SpecialKeyboardKey = "INSERT"
	KEYBOARD_MENU        types.SpecialKeyboardKey = "MENU"

	KEYBOARD_NUMPAD_0    types.SpecialKeyboardKey = "NUMPAD_0"
	KEYBOARD_NUMPAD_1    types.SpecialKeyboardKey = "NUMPAD_1"
	KEYBOARD_NUMPAD_2    types.SpecialKeyboardKey = "NUMPAD_2"
	KEYBOARD_NUMPAD_3    types.SpecialKeyboardKey = "NUMPAD_3"
	KEYBOARD_NUMPAD_4    types.SpecialKeyboardKey = "NUMPAD_4"
	KEYBOARD_NUMPAD_5    types.SpecialKeyboardKey = "NUMPAD_5"
	KEYBOARD_NUMPAD_6    types.SpecialKeyboardKey = "NUMPAD_6"
	KEYBOARD_NUMPAD_7    types.SpecialKeyboardKey = "NUMPAD_7"
	KEYBOARD_NUMPAD_8    types.SpecialKeyboardKey = "NUMPAD_8"
	KEYBOARD_NUMPAD_9    types.SpecialKeyboardKey = "NUMPAD_9"
	KEYBOARD_NUMPAD_LOCK types.SpecialKeyboardKey = "NUMPAD_LOCK"

	KEYBOARD_NUMPAD_DECIMAL types.SpecialKeyboardKey = "NUMPAD_DECIMAL"
	KEYBOARD_NUMPAD_PLUS    types.SpecialKeyboardKey = "NUMPAD_PLUS"
	KEYBOARD_NUMPAD_MINUS   types.SpecialKeyboardKey = "NUMPAD_MINUS"
	KEYBOARD_NUMPAD_MUL     types.SpecialKeyboardKey = "NUMPAD_MUL"
	KEYBOARD_NUMPAD_DIV     types.SpecialKeyboardKey = "NUMPAD_DIV"
	KEYBOARD_NUMPAD_ENTER   types.SpecialKeyboardKey = "NUMPAD_ENTER"
	KEYBOARD_NUMPAD_EQUAL   types.SpecialKeyboardKey = "NUMPAD_EQUAL"

	KEYBOARD_AUDIO_VOLUME_MUTE types.SpecialKeyboardKey = "AUDIO_VOLUME_MUTE"
	KEYBOARD_AUDIO_VOLUME_DOWN types.SpecialKeyboardKey = "AUDIO_VOLUME_DOWN"
	KEYBOARD_AUDIO_VOLUME_UP   types.SpecialKeyboardKey = "AUDIO_VOLUME_UP"
	KEYBOARD_AUDIO_PLAY        types.SpecialKeyboardKey = "AUDIO_PLAY"
	KEYBOARD_AUDIO_STOP        types.SpecialKeyboardKey = "AUDIO_STOP"
	KEYBOARD_AUDIO_PAUSE       types.SpecialKeyboardKey = "AUDIO_PAUSE"
	KEYBOARD_AUDIO_PREV        types.SpecialKeyboardKey = "AUDIO_PREV"
	KEYBOARD_AUDIO_NEXT        types.SpecialKeyboardKey = "AUDIO_NEXT"
)

type Keyboard interface {
	SendInputKeyChar(key rune, down bool) error
	SendInputKeySpecialKey(key types.SpecialKeyboardKey, down bool) error
}
